services:
  policebot:
    profiles: ["production"]
    container_name: policebot
    image: ghcr.io/cubeur-manchot/policebot:latest
    restart: unless-stopped
    env_file: .env
  policebot-dev:
    profiles: ["development"]
    container_name: policebot-dev
    build: .
    env_file: .env
