version: '3.8'
services:
  policebot:
    container_name: policebot
    restart: always
    build: .
    env_file: .env
    volumes:
      - type: bind
        source: ./infractions.json
        target: /infractions.json
